### ISSUE TITLE
advice

### ISSUE THREAD

**Issue by N3verL4nd** [name5566/merry#2]
-- 增加命令 say
addcommand{ command = 'say', func = function(arg)
    -- 在 merry 的命令窗口输入的 say 命令的参数将以字符串的形式传递给 arg
    message(arg)
end }

应为addCommand

ALT+T打开cmd，只在xp下可以打开当前目录，WIN7是不可以的（getWindowText得到的不是路径）

**Comment by name5566** [comment]
Windows 下，在资源管理器中，使用 Merry 打开 DOS 窗口且设定工作目录为资源管理器所在目录。首先，我们应该设置资源管理器在标题栏显示完整路径，使得 Merry 可以获取到这个路径，设置的方法为：资源管理器 --- 工具 --- 文件夹选项 --- 查看 --- 标题栏显示完整路径。然后我们就可以在打开 DOS 窗口的时候设定工作目录了：

```
addCommand{ command = 'cmd', key = 'A-T', func = function()
    local window = getForegroundWindow()
    local dir = getWindowText(window)
    shellExecute('cmd', '', dir)
end }
```
